baseURL               = "https://chemtour.github.io"
languageCode          = "zh-CN"
title                 = "AIHG导航"
theme                 = "WebStack-Hugo"
preserveTaxonomyNames = true
disablePathToLower    = true
hasCJKLanguage        = true
publishDir            = "public"				# 站点静态文件保存目录


[params]
    author        = "AIHG"
    description   = "先知起航 材化先知"
    upload        = "https://adu8.top/apply"      # 左侧导航栏的"网站提交"
    about         = "https://adu8.top/about"	          # 左侧导航栏的"关于导航"页面(./about)
    repository    = "https://github.com/shenweiyan/WebStack-Hugo"  
    enablePreLoad = true					# 网站完全打开前预加载动画
    textPreLoad   = "AIHG 材化先知"				# 预加载的动画文字, 只有当enablePreLoad=true时生效
    expandSidebar = false					# 默认展开左侧边导航栏
    logosPath     = "assets/images/logos"			# 网站每个导航地址logo存放地址
    defaultLogo   = "assets/images/logos/default.webp"		# logo图片资源不存在或者错误时, 默认显示的logo; 该参数如为空,将会一直加载对应的logo,直至成功
    nightMode     = false					# 默认站点为深色(夜间)模式
    yiyan         = true                         		# 默认启用一言服务

[params.seo]    
    baiduhmid       = ''	# 百度统计 hm.src 的 ID
    baiduSiteVer    = ''			# 百度HTML标签验证(baidu-site-verification)
    tj51laid        = ''                        		# 51.LA 网站统计
    tj51lack        = ''
    GoogleAdsClient = ''					# Google AdSense 

[params.qweather]
    key = "085791e805a24491b43b06cf58ab31e7"

[params.images]
    favicon           = "assets/images/favicon.png"
    searchImageL      = "assets/images/bg-dna.jpg"		# 搜索部分浅色背景图
    searchImageD      = "assets/images/bg-dna.jpg"		# 搜索部分深色背景图
    logoExpandLight   = "assets/images/bt8-expand-light.png"
    logoExpandDark    = "assets/images/bt8-expand-dark.png"
    logoCollapseLight = "assets/images/bt.png"
    logoCollapseDark  = "assets/images/bt.png"
    
[markup.goldmark.renderer]
    unsafe = true

[params.footer]
    copyright = "<a id="adu8" href="https://www.adu8.top"><img src="https://www.adu8.top/template/poto/xzwx2023.jpg"  width="100" height="100" title="先知微信公众号" alt="材化先知" border="3" /></a><a href="https://www.adu8.top"><img src="https://www.adu8.top/template/poto/xztt2023.png"  width="100" height="100" title="先知今日头条号" alt="材化先知" border="3" /></a><br>Copyright &copy; 2023 - {year} By <a href="/">先知起航</a>.  All Rights Reserved.<br>本网站使用CC BY-NC-ND 4.0协议共享，链接均采集自互联网，仅收录网站，不对其链接网站内容或交易负责。 <br>本网站中链接所得的网页，以及网页中所有内容，均系第三方网站制作提供，所有权归其所有。 如有内容侵犯了你的权益，请联系删除相关内容，联系邮箱：chemtour@gmx.com <br><a href="https://beian.miit.gov.cn/" target="_blank">浙ICP备2023047226号-1</a>"

[taxonomies]
  tag = "tags"
  series = "series"
  category = "categories"